# List of texts to search for
search_texts_1 = [
    "MM_fct_GO_SPINNING_SPEED",
    "MM_fct_HOMING_DRIVES",
    "MM_fct_MOVE_YHD_DOWN",
    "MM_fct_OPEN_YSD",
    "MM_fct_PREPARE_CUTTING",
    "MM_fct_REDUCE_YSD_FOR_YHD",
    "MM_fct_SPINNING_DELAY",
    "MM_fct_START_FEEDING",
    "MM_fct_THREAD_IN_FWD",
    "MM_fct_RC_CONFIRM_CUT",
    "MM_fct_RC_HOMING",
    "MM_fct_RC_PREPARE_CUTTING",
    "MM_fct_RC_START_SEARCH",
    "MM_fct_RC_WAIT_PIE_PERM",
    "MM_fct_RC_WT_TRANS_TAIL",
    "MM_fct_AVOID_CROSS_YARN",
    "MM_fct_DISP_AFTER_TRANS",
    "MM_fct_DISP_BEFORE_TRANS",
    "MM_fct_DRAG_YARN_NOK",
    "MM_fct_DRAG_YARN_OK",
    "SM_fct_WCS_STOP_WUF",
    "MM_fct_STOP_AFTER_YB",
    "MM_fct_RP_DONE",
    "MM_fct_RP_LIFT_TLD",
    "MM_fct_RP_MOVE_YHD_DOWN",
    "MM_fct_HOMING_CMD",
    "MM_fct_INIT",
    "MM_fct_PRE_BOOTING_COMP",
    "MM_fct_PREP_TIDY_UP",
    "MM_fct_SAFE_STATE",
    "MM_fct_SW_OFF_SSV",
    "MM_fct_TIDY_UP"
]

search_texts = {
    "MM_fct_GO_SPINNING_SPEED": {'id': 1, 'comment': " <<< Action with YSD >>>"},
    "MM_fct_HOMING_DRIVES": {'id': 2, 'comment': " <<< Action with YSD >>>"},
    "MM_fct_MOVE_YHD_DOWN": {'id': 3, 'comment': " <<< Action with YSD >>>"},
    "MM_fct_OPEN_YSD": {'id': 4, 'comment': " <<< Action with YSD >>>"},
    "MM_fct_PREPARE_CUTTING": {'id': 5, 'comment': " <<< Action with YSD >>>"},
    "MM_fct_REDUCE_YSD_FOR_YHD": {'id': 6, 'comment': " <<< Action with YSD >>>"},
    "MM_fct_SPINNING_DELAY": {'id': 7, 'comment': " <<< Action with YSD >>>"},
    "MM_fct_START_FEEDING": {'id': 8, 'comment': " <<< Action with YSD >>>"},
    "MM_fct_THREAD_IN_FWD": {'id': 9, 'comment': " <<< Action with YSD >>>"},
    "MM_fct_RC_CONFIRM_CUT": {'id': 10, 'comment': " <<< Action with YSD >>>"},
    "MM_fct_RC_HOMING": {'id': 11, 'comment': " <<< Action with YSD >>>"},
    "MM_fct_RC_PREPARE_CUTTING": {'id': 12, 'comment': " <<< Action with YSD >>>"},
    "MM_fct_RC_START_SEARCH": {'id': 13, 'comment': " <<< Action with YSD >>>"},
    "MM_fct_RC_WAIT_PIE_PERM": {'id': 14, 'comment': " <<< Action with YSD >>>"},
    "MM_fct_RC_WT_TRANS_TAIL": {'id': 15, 'comment': " <<< Action with YSD >>>"},
    "MM_fct_AVOID_CROSS_YARN": {'id': 16, 'comment': " <<< Action with YSD >>>"},
    "MM_fct_DISP_AFTER_TRANS": {'id': 17, 'comment': " <<< Action with YSD >>>"},
    "MM_fct_DISP_BEFORE_TRANS": {'id': 18, 'comment': " <<< Action with YSD >>>"},
    "MM_fct_DRAG_YARN_NOK": {'id': 19, 'comment': " <<< Action with YSD >>>"},
    "MM_fct_DRAG_YARN_OK": {'id': 20, 'comment': " <<< Action with YSD >>>"},
    "SM_fct_WCS_STOP_WUF": {'id': 21, 'comment': " <<< Action with YSD >>>"},
    "MM_fct_STOP_AFTER_YB": {'id': 22, 'comment': " <<< Action with YSD >>>"},
    "MM_fct_RP_DONE": {'id': 23, 'comment': " <<< Action with YSD >>>"},
    "MM_fct_RP_LIFT_TLD": {'id': 24, 'comment': " <<< Action with YSD >>>"},
    "MM_fct_RP_MOVE_YHD_DOWN": {'id': 25, 'comment': " <<< Action with YSD >>>"},
    "MM_fct_HOMING_CMD": {'id': 26, 'comment': " <<< Action with YSD >>>"},
    "MM_fct_INIT": {'id': 27, 'comment': " <<< Action with YSD >>>"},
    "MM_fct_PRE_BOOTING_COMP": {'id': 28, 'comment': " <<< Action with YSD >>>"},
    "MM_fct_PREP_TIDY_UP": {'id': 29, 'comment': " <<< Action with YSD >>>"},
    "MM_fct_SAFE_STATE": {'id': 30, 'comment': " <<< Action with YSD >>>"},
    "MM_fct_SW_OFF_SSV": {'id': 31, 'comment': " <<< Action with YSD >>>"},
    "MM_fct_TIDY_UP": {'id': 32, 'comment': " <<< Action with YSD >>>"}
}